### PR TITLE
Update Files.es-ES.xlf

### PR DESCRIPTION
**Pull request by xPoppyx**
It wasn't fully translated into Spanish, so I added the missing ones.
the texts in the app will need more space because some words are longer in Spanish

### CODE REVIEW

**Comment by yaichenbaum** [comment]
Can you create a list of which areas need more space to fit the strings?

**Comment by xPoppyx** [comment]
Captura de pantalla (170)
Captura de pantalla (171)
Captura de pantalla (172)
Captura de pantalla (163)
Captura de pantalla (164)
Captura de pantalla (165)
Captura de pantalla (167)
Captura de pantalla (168)
Captura de pantalla (169)
Captura de pantalla (174)

**Comment by xPoppyx** [comment]
I did not find "Drives" in the file, it must be translated to: **Unidades**
"Settings" is shown in Spanish in some parts and not in others.
Captura de pantalla (176)
-----------------------------------------------------------------------------
Captura de pantalla (177)

**Comment by yaichenbaum** [comment]
Have you actually tested in the app? Most of the places you mentioned should automatically resize based on the string length.

**Comment by xPoppyx** [comment]
I don't have the necessary tools to do it, and with the internet speed I have, it would take time to download Visual Studio

**Comment by yaichenbaum** [comment]
@xPoppyx No worries, I am fairly sure this is going to be handled. I added a string that should take care of the settings tab. Feel free to update this pull request or open a new one to translate it.

**Pull request closed without merging**
