### PR TITLE
Feat: Optional acrylic sidebar

### PR DESCRIPTION
**Pull request by lampenlampen**
Solves #193. 

Changes:
1. new setting in "Personalization":
acrylicSidebar_settings

2. Acrylic sidebar:
acrylicSidebar

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@lampenlampen Can you change the option to be a toggle switch? Additionally its important to note that we made changes to the side bar in the v0.7 branch that may not work with your changes, can you confirm that they are compatible?

**Comment by duke7553** [comment]
@lampenlampen This should be based off the v0.7 changes branch, and use these Acrylic brushes to match our design:
Light/Default:
`<AcrylicBrush FallbackColor="#19000000" BackgroundSource="HostBackdrop" TintOpacity="0.7" Windows10version1903:TintLuminosityOpacity="0.9" TintColor="White"/>`
Dark:
`<AcrylicBrush FallbackColor="Black" BackgroundSource="HostBackdrop" TintOpacity="0.7" Windows10version1903:TintLuminosityOpacity="0.9" TintColor="Black"/>`

**Comment by yaichenbaum** [comment]
@lampenlampen Are you able to make the changes requested?

**Comment by lampenlampen** [comment]
I have some problems with the fallback color, if the windows is not active.

Files-AcrylicSidebar_FallbackColor

**Comment by yaichenbaum** [comment]
@lampenlampen Most likely you would need to modify the NavMenus template.

**Pull request merged**
