### PR TITLE
Locked the search button since it is not yet implemented

### PR DESCRIPTION
**Pull request by yaichenbaum**

### CODE REVIEW

**Comment by lampenlampen** [comment]
I would also disable the search bar in the settings

**Comment by lampenlampen** [comment]
Maybe we should consider to hide features, that are not working, for a better user experience for the official launch.

**Comment by duke7553** [comment]
I plan on starting my work for Search around May 12, but if it isn't satisfactory, then it will live behind a flag on Launch until it's ready.

But yes, generally any feature not ready needs to be disabled or behind a flag.

**Comment by yaichenbaum** [comment]
@duke7553 I would hesitate to add a flag that would imply that some functionality will work if enabled until there is actually something to enable, so I think it should be disabled until then.

**Comment by lampenlampen** [comment]
I would create a code flag for these features and if suitable we can expose those in the experimental settings page, when ready for testing.

**Pull request merged**
