### PR TITLE
Feat/drives refactoring

### PR DESCRIPTION
**Pull request by lampenlampen**
So i think i'm ready.

### CODE REVIEW

**Comment by duke7553** [comment]
@lampenlampen Startup Crash info: 
Windows.Graphics.Display: GetForCurrentView must be called on a thread that is associated with a CoreWindow.

**Comment by duke7553** [comment]
I'm guessing it has to do with the consent dialog which displays on startup because this exception only occurs when running in a debugger and file system access is disabled.

**Comment by lampenlampen** [comment]
So i can reproduce the crash, if the debugging option "Only my code" is enabled. If disabled, the crash does not occur.

**Comment by lampenlampen** [comment]
A guess:
`consentDialog.ShowAsync()` is somewhere called, before the Application `CoreWindow` is created, thus it fails to display the dialog ui.
And somehow the debugger delays the creation of the `CoreWindow`.

**Comment by lampenlampen** [comment]
I could fix it, by delaying the creation of the `SettingsViewModel`, until the constructor of `App` is called.

**Comment by duke7553** [comment]
@lampenlampen I'm still encountering a crash for some reason on the latest changes

**Comment by lampenlampen** [comment]
Yes there is a `NullReferenceException` at https://github.com/duke7553/files-uwp/blob/69902d4bb3e3f2d46b33c842057d2a982d66aaa5/Files/Filesystem/ListedItem.cs#L45
because `datetimeformat` is `null` at a fresh install.

We need to set a default value at startup, if it is null.
At https://github.com/duke7553/files-uwp/blob/69902d4bb3e3f2d46b33c842057d2a982d66aaa5/Files/View%20Models/SettingsViewModel.cs#L45
we should set a default value, if `datetimeformat` is null.

What should the default value be?

**Comment by yaichenbaum** [comment]
The setting view model should have a default for every setting, the default for date and time format should be friendly date and times. For example "2 days ago".

**Comment by lampenlampen** [comment]
So we can choose between `Application` and `System`. I set it now to `System`.

**Comment by yaichenbaum** [comment]
I think `Application` is the one with friendly dates...

**Comment by lampenlampen** [comment]
They are both with friendly dates.

<table>
<tr>
<th>
Application
</th>
<td>
`4 days ago`, `15 hours ago`, `Saturady, October 12, 2019`
</td>
</tr>
<tr>
<th>
System
</th>
<td>
`4 days ago`, `15 hours ago`, `10/12/2019 5:14 PM`
</td>
</tr>
</table>

**Comment by yaichenbaum** [comment]
Ok, so lets set the default to application. That is how it was in previous versions of Files as well.

**Comment by yaichenbaum** [comment]
Great, is this pull request ready for review now?

**Comment by lampenlampen** [comment]
Yes fixed a last bug, but should be ready now 👍.

**Pull request merged**
