### PR TITLE
Moved image to top

### PR DESCRIPTION
**Pull request by nainardev**
Users first check for screenshots. Include as early as possible

### CODE REVIEW

**Comment by szaimen** [comment]
I like this idea 👍

**Comment by yaichenbaum** [comment]
I think build status should still be on the top, how about moving it on top of the instructions for building from the source code?

**Comment by szaimen** [comment]
Fine by me 👍

**Comment by nainardev** [comment]
Can you do it? I'm having trouble editing

**Comment by nainardev** [comment]
Why????

**Comment by yaichenbaum** [comment]
> Why????

@nainardev What do you mean by this?

**Comment by nainardev** [comment]
Why you moved image to bottom again?

**Comment by yaichenbaum** [comment]
@nainardev I moved it underneath the build status.

**Comment by nainardev** [comment]
Reeaady to merge?

**Pull request merged**
