### PR TITLE
Overall code formatting and re-arranging and some minor touch-ups

### PR DESCRIPTION
**Pull request by carlosrfernandez**
Hey, 

just wanted to propose some changes. 
I've created some folders and cleaned up some of the code. 

Basically it's all a bit difficult to navigate right now. 

Some of the changes include: 
- separate each class to a separate file (so 1 class per file)
- fixed some namespaces
- removed blank spaces where necessary
- improved the code that goes through available partitions/drives

This is just an idea, but since you know a lot more about doing UI work, you can use this PR to basically split things a bit better than what I've done. 

Let me know if you have any questions or comments and I'd be happy to change things.

### CODE REVIEW

**Comment by duke7553** [comment]
Sorry, I just made some necessary conflicting changes in the master branch. This rearranging LGTM, so I am going to try to "port" your changes to work with the new code.

**Comment by duke7553** [comment]
Great work btw

**Comment by duke7553** [comment]
I went ahead and pushed the new version to master.

**Comment by carlosrfernandez** [comment]
Make sure you tag issues with appropriate things, like 'help-wanted' if you'd like help

**Comment by duke7553** [comment]
@carlosrfernandez It's funny you say that, I was just in the process of writing an issue and tagging it for you!

**Pull request closed without merging**
