### PR TITLE
Fixed visiblity issue for close, minimize, and maximize in light mode.

### PR DESCRIPTION
**Pull request by ATecSolution**
Fixed visiblity issue for close, minimize, and maximize in light mode.

### CODE REVIEW

**Comment by duke7553** [comment]
Wow, nice work. Has this been tested to fix the problem when the user changes the theme to differ from the System theme? If so, LGTM

**Comment by duke7553** [comment]
I noticed the same thing happens with the Dark theme, when system is set to Light mode. Would this PR fix that too?
40e8a604-618c-4b90-958e-749c25f05660 png

**Comment by ATecSolution** [comment]
In my testing it did.

**Comment by duke7553** [comment]
Well, in that case...

**Pull request merged**
