### PR TITLE
v0.7.6

### PR DESCRIPTION
**Pull request by yaichenbaum**

### CODE REVIEW

**Comment by xPoppyx** [comment]
will critical bugs be fixed first before updating the app in the microsoft store?

**Comment by duke7553** [comment]
@xPoppyx Hi. Thanks for your feedback items. We're in the process of rethinking the way we evaluate feedback for subsequent releases. I think you will like what comes out of this regarding stability and bug fixes. 

If you mention the specific issues in question, I can tell you if they're fixed or not.

**Comment by xPoppyx** [comment]
I was just asking since in the Microsoft store the app has not yet been updated to version 0.7.6 to test the new features

**Comment by duke7553** [comment]
@xPoppyx Yes, v0.7.6 should be in certification now.

**Pull request merged**
