### PR TITLE
Fixed app crash

### LINKED ISSUE #720: App crash in release mode
**Describe the bug**
Sometimes app crash right after launch.

**To Reproduce**
1. Build app in release mode and deploy
2. Start app
3. If it did not crash, restart app

**Expected behavior**
Expected normal start without crash

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909 18363.815]
 - App version: [v0.7.9]

**Additional context**
Built from develop branch.

### PR DESCRIPTION
**Pull request by tsvietOK**
Var TintLuminosityOpacity removed as it has the same value(0.9) for light and dark themes.
Renamed class
Fixes #720

### CODE REVIEW

**Comment by duke7553** [comment]
Thanks for this PR. Could you please explain how this one fixes the crash?

**Comment by tsvietOK** [comment]
@duke7553 Read my comment [here](https://github.com/duke7553/files-uwp/issues/720#issuecomment-621927449)

**Comment by tsvietOK** [comment]
@duke7553 May be you can realize possible reasons why setting a value to var causes app crash in release mode

**Pull request merged**
