### PR TITLE
Merge NewUI to master

### PR DESCRIPTION
**Pull request by duke7553**
This is the PR that accompanies the recent announcement regarding the new direction Files UWP is headed towards in order to differentiate us from the competition. Constituting this are the introduction and implementation of several new layouts for the app. These are not related to the "item layouts" within the existing single layout, but rather new methods to interface with the filesystem that will intelligently adapt to your device type, form factor, and skill level. So far, work is underway on the first, known as _Project Mumbai_, which increases the overall density of UI elements in a way that's suitable for desktop users and improves familiarity for those who have previously used Windows Explorer. Also on the roadmap for the near future are _Project Greenland_ for tablet users, _Project Shanghai_ for users of taller (non-landscape) devices like mobile phones, and _Project Mesopotamia_ for users comfortable with the bread-and-butter interface trends that made up WinFile. (See list below for mockups, development updates, and screenshots)

Of course, the underlying goal is to ensure **all of these layouts** take advantage of the Fluent Design language elements that Microsoft has designed in a way that keeps Files UWP the most innovative and customizable UWP File Explorer. I welcome contributions from the community. As always, keep up the great feedback!

-- Luke Blevins, Lead Developer of Files UWP

### Project Mumbai
Annotation 2019-05-08 215041

_Notes: Work inspired from Michael West's Twitter Concepts_

Development Updates:
- Steady Progress has been made on coding this layout (4/12/2019)
- It has been quite easy hooking up the commands to the new Ribbon (4/14/2019)
- Hit some obstacles while implementing Instance Tabs, so I spend the weekend fixing other bugs (4/28/2019)
- Had to heavily modify code from almost every file to support separate instances. However, I am proud to say the instance tabs are mostly completed. Further, I'm working on rounding the corners of some UI elements to match the Microsoft aesthetic. (5/8/2019)

### Project Mesopotamia
wyoy0onlysf21
_Notes: This is a Fluent redesign of the WinFile program. Code is still incomplete as pictured above._

Development Updates:
- On hold until I can study the UWP TreeView and clean up the existing codebase (1/2/2019)
- Formerly/Internally known as ClassicView (4/15/2019)

### Project Greenland
--------- NO IMAGE YET -----------
_Notes: N/A at this time_

Development Updates: 
- Trialing different UI types with family members to see which one works best with tablets/touch input (3/15/2019)
- Interpreting results to decide on a high-quality implementation, still in planning phase (4/14/2019)

### Project Shanghai
Annotation 2019-04-15 190745
_Notes: This is a screenshot of the current Windows Mobile File Explorer. I plan on taking inspiration from this UI, when appropriate._

Development Updates:
- I don't own a Windows Mobile device, so it will be hard to test for this look since emulator support has been dropped from VS 2019 (4/15/2019)
- I will likely work on this UI from a resized window to simulate the screensize of Windows Mobile devices (4/15/2019)
- Marking as **low-priority**; I don't want this layout to hold up the release of the NewUI (4/15/2019)

### When will this be released?
**For Code Contributors:** All work is being done in the branch `newui`.
**For Testers:** When it's ready. The new layouts will be released gradually, likely with many bugs, so I will keep everyone posted on the release page and appropriate notes.
**For the General Public (in the Microsoft Store):** When issue reports have declined dramatically and there is a clear, feasible path to a completely-finished product.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
Looking really good!

**Comment by Mohsens22** [comment]
I'm looking for a UI like this: 
image

image

**Comment by westonsheisey** [comment]
I like Project Mumbai best....

**Comment by Inversil** [comment]
This looks really good! Have you thought of implementing tabs into the new UI? People online (including me) are really hungry for good explorer alternatives with tabs ever since sets were cut.

**Comment by duke7553** [comment]
@Inversil Yes, the final UI will have tabs. They are on my roadmap.

**Comment by duke7553** [comment]
I think it's now ready to be merged into master.

**Pull request merged**
