### PR TITLE
Fixed the problem of Settings page when in non-English environment.

### PR DESCRIPTION
**Pull request by creeperlv**
Since File UWP supports multi-language, settings page is broken, so I find a way of fixing it.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@creeperlv Thank you for opening this pull request, this issue has already been fixed in both the `develop` and `master` branches, can you verify this is still an issue with v0.7.1?

**Comment by yaichenbaum** [comment]
What we are currently doing is checking the tag, which is not localized, but after looking over your commit, I believe it is a cleaner solution.

**Comment by creeperlv** [comment]
<del>Yes, I checked the code in `master`, I find that you are using ToString() to determine which page the user wants to view, however, the in non-English environment, it will return other string instead of `Appearance` ...</del>
Thank you.

**Comment by yaichenbaum** [comment]
@creeperlv Before I merge your pull request, would you be able to resolve the merge conflicts?

**Comment by creeperlv** [comment]
I am new of using pull requests, I have no idea of resolving conflicts. Could you help me?

**Comment by creeperlv** [comment]
Should I just overwrite lines in `master` to lines in `develop`?

**Comment by yaichenbaum** [comment]
In this case, since the change is small, I would recommend copying your changes over to the `develop` branch and then to create a new pull request. We recommend changes made to the code base to be based on the latest in `develop` to avoid scenarios like this.

**Comment by creeperlv** [comment]
Okay, thx. I'll do it immediately.

**Comment by yaichenbaum** [comment]
@creeperlv Thank you so much, we appreciate your help to improve Files UWP 🙂

**Comment by creeperlv** [comment]
You are welcome, I like this software. 😆

**Pull request closed without merging**
