### PR TITLE
Choose Terminal Applications

### PR DESCRIPTION
**Pull request by lampenlampen**
# Description

- Creates a `terminals.json` in the "local"-AppFolder with terminal profiles ([file](https://github.com/lampenlampen/files-uwp/blob/feat/Terminal/Files/Assets/terminal/terminal.json)). As default profile the "cmd"-profile is included. A second commented profile for powershell is also included. It seems the new Windows Terminal currently does not support launching in a specific directory from commandline ([link](https://github.com/microsoft/terminal/pull/4023#issue-355223599)).
- Includes a combobox in the settings to choose between the profiles.

# UI

Light | Dark
------------ | -------------
files_terminal_settings_white | files_terminal_settings_dark

# Question

1. [JSON.Net](https://www.newtonsoft.com/json) as dependency?
2. `terminal.json`-schema? At the moment you can specify a name, a description, the executable path, arguments and an icon, but only the name, the path and the arguments are used.

### CODE REVIEW

**Comment by SOI7** [comment]
@lampenlampen Judging from this post ([https://github.com/microsoft/terminal/issues/620](url)) it seems that now it's possible to launch Windows Terminal from a directory. The command line in the address bar is `wt.exe` and to enable the starting directory you need to add  `"startingDirectory": "."` in the default profile used in Terminal. I tried this in the Win32 Explorer and works like a charme, and adding this to the terminal.json should be straghtforward (I tried this on 0.7.1 as well, the command works for opening Terminal but none of the consoles actually launches in the folder I run the command from, not even cmd)

**Comment by lampenlampen** [comment]
Hey,

Opening in a directory is currently not supported. This feature needs some work that is currently in the 'settings-vm'-branch.


________________________________
Von: SOI_7 <notifications@github.com>
Gesendet: Donnerstag, 30. Januar 2020 00:39
An: duke7553/files-uwp
Cc: lampenlampen; Mention
Betreff: Re: [duke7553/files-uwp] Choose Terminal Applications (#361)


@lampenlampen<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flampenlampen&data=02%7C01%7C%7Cd8265e157edd49a74d2008d7a51482c8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637159379811957115&sdata=cx5Wm1cCpSKgAbD6vRUzaRq4IgaFevvAjrBPJr7JyyU%3D&reserved=0> Judging from this post (https://github.com/microsoft/terminal/issues/620<url>) it seems that now it's possible to launch Windows Terminal from a directory. The command line in the address bar is wt.exe and to enable the starting directory you need to add "startingDirectory": "." in the default profile used in Terminal. I tried this in the Win32 Explorer and works like a charme, and adding this to the terminal.json should be straghtforward (I tried this on 0.7.1 as well, the command works for opening Terminal but none of the consoles actually launches in the folder I run the command from, not even cmd)

**Comment by yaichenbaum** [comment]
@lampenlampen We ported over the work in `settings-vm` to `v0.7.1 changes`.

**Comment by lampenlampen** [comment]
@SOI7 I missunderstand you. I thought you talked about opening files in a specific directory.

I checked and I am able to open cmd in the specified directory.

**Comment by SOI7** [comment]
> @SOI7 I missunderstand you. I thought you talked about opening files in a specific directory.
> 
> I checked and I am able to open cmd in the specified directory.

No, I was talking about opening the preferred terminal app (specified in Files settings) from a folder in Files. I simply bumped you because in the OP you stated "It seems the new Windows Terminal currently does not support launching in a specific directory from commandline", and now things have changed

**Comment by lampenlampen** [comment]
So i played with Windows Terminal a bit.

1. You cannot pass a path to open in Windows Terminal. So for me it seems, that Windows Terminal simply opens the `workingDirectory` of the process it was launched from. Therefore it works from `terminals` and the `explorer`, but i think it will not work with `files`, because it does not change it's `workingDirectory` to the folder currently displayed. \
\
Therefore we have to wait until Windows Terminal support passing a path to it.

2. On my machine I'm able to open a directory in cmd and powershell. So for this issue i suggest opening a bug report here and include your `profiles.json`.

**Pull request merged**
