### PR TITLE
Perform french translations

### PR DESCRIPTION
**Pull request by KaKi87**
Remaining TODO : `SettingsAppearanceAcrylicSidebar.Text`, + some [unclear details](https://github.com/duke7553/files-uwp/issues/37#issuecomment-583818576)

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@KaKi87 Would you like me to hold off merging until you finish?

**Comment by KaKi87** [comment]
Yes, thanks

**Comment by KaKi87** [comment]
Done.

**Comment by yaichenbaum** [comment]
@KaKi87 Thank you so much!

**Pull request merged**
